export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT';
export const GET_PRODUCT_BY_SELLER_ID = 'GET_PRODUCT_BY_SELLER_ID';
export const GET_PRODUCT_BY_KEY = 'GET_PRODUCT_BY_KEY';
