// PRODUCT
export const GET_PRODUCT = 'GET_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DETELE_PRODUCT = 'DETELE_PRODUCT';
export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT';
export const GET_PRODUCT_BY_SELLER_ID = 'GET_PRODUCT_BY_SELLER_ID';
export const GET_PRODUCT_BY_KEY = 'GET_PRODUCT_BY_KEY';


// PROFILE
export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const GET_USER_PROFILE_BY_ID = 'GET_USER_PROFILE_BY_ID';

// TRANSACTION
export const GET_PRODUCT_TRANSACTION_BY_ID = 'GET_PRODUCT_TRANSACTION_BY_ID';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';